### ISSUE TITLE
No 'version' key in the manifest

### ISSUE THREAD

**Issue by jon-daemon** [fishbigger/HomeAssistant-Tapo-P100-Control#15]
I get this warning:
```No 'version' key in the manifest file for custom integration 'tapo_p100_control'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'tapo_p100_control'```

**Comment by shiner66** [comment]
@fishbigger you might want to close that too haha!

**Comment by fishbigger** [comment]
Yes :)
