### ISSUE TITLE
Offline usage? 

### ISSUE THREAD

**Issue by kpp39** [fishbigger/HomeAssistant-Tapo-P100-Control#18]
Can you explain the mechanism that used by this integration? Will it work in local network, when there is no internet connection, or this integration interracts with TP-Link server?

**Comment by Mafuju** [comment]
That's a really good question! I want to know that, too.

**Comment by fishbigger** [comment]
The integration works for polling the plug locally so it can work without the tplinkcloud and an internet connection. For more information you can see [k4czp3r post](https://k4czp3r.xyz/reverse-engineering/tp-link/tapo/2020/10/15/reverse-engineering-tp-link-tapo.html) on it which explains the exact api call and how it all works. Hope this helps :)

**Comment by kpp39** [comment]
> The integration works for polling the plug locally so it can work without the tplinkcloud and an internet connection. For more information you can see [k4czp3r post](https://k4czp3r.xyz/reverse-engineering/tp-link/tapo/2020/10/15/reverse-engineering-tp-link-tapo.html) on it which explains the exact api call and how it all works. Hope this helps :)

Thank you ! A great explaination !
