### ISSUE TITLE
No 'version' key in the manifest file for custom integration

### ISSUE THREAD

**Issue by Mafuju** [fishbigger/HomeAssistant-Tapo-P100-Control#19]
Hey!
 I get the following error message in Home Assistant when I try to add a Taco-P100 plug:

`Logger: homeassistant.loader
Source: loader.py:786 
First occurred: 18:46:02 (1 occurrences) 
Last logged: 18:46:02

No 'version' key in the manifest file for custom integration 'tapo_p100_control'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'tapo_p100_control'`

I would love to see a solution to this!

**Comment by richard-scott** [comment]
Please download the latest from the "[main](https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control/branches)" branch, as this fix is already there.

**Comment by Mafuju** [comment]
Thank you! Now it is working.
