### ISSUE TITLE
Incorrect type. Expected "array" Error

### ISSUE THREAD

**Issue by Clairyfy** [fishbigger/HomeAssistant-Tapo-P100-Control#23]
Hello! when I am putting the Tapo P100 Plug Control code in configuration.yaml I get an error that says
Incorrect type. Expected “array”. I am new to home assistant so I don’t know how to fix this. Thank you. 
I am using Visual Studio Code add on if that makes a difference

**Comment by richard-scott** [comment]
What configuration did you use?

**Comment by Clairyfy** [comment]
configuration?
Configuration.yaml with the Visual Studio code editor

**Comment by richard-scott** [comment]
No, I mean what switches YAML did you add to your configuration.yaml file 👍

**Comment by Clairyfy** [comment]
Still don't understand what you mean. I can show my code if you want.

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#P100 or P105 Plug
switch:
    platform: tapo_p100_control
    ip_address: 192.168.x.x
    email: example.test@gmail.com
    password: Password123

**Comment by Clairyfy** [comment]
If you mean Switches.Yaml or something like that I don't have that.

**Comment by richard-scott** [comment]
Ok, did you indent the lines where required. YAML uses spaces to format the code.

The bottom 4 lines in the example text all need to start with two spaces.

**Comment by Clairyfy** [comment]
Yeah I did that
![Capture](https://user-images.githubusercontent.com/84933127/120152998-7983f380-c1ee-11eb-99ad-821b98858900.PNG)
It looks like this

**Comment by richard-scott** [comment]
Ok, comment that section and reload Home Assistant... I don’t think this section is the problem. If this section is the problem, then your error will go away when commenting this out.

**Comment by Clairyfy** [comment]
Works now. Thank you!.
