### ISSUE TITLE
Power measurement with P110

### ISSUE THREAD

**Issue by diibify** [fishbigger/HomeAssistant-Tapo-P100-Control#40]
Tapo P110 as a switch is working for now. But I bought the sockets in order to integrate the power measurement into my HA. Is there any way to do so?

`      switch_steckdose1_watt:
        friendly_name_template: "{{ states.switch.steckdose1.name}} Leistung"
        value_template: '{{ states.switch.steckdose1.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'`

Above code with adapted name didnt work. Any idea?

**Comment by kenhayward** [comment]
I would be interested in adding P110 energy monitoring support, before I do this and add a pull request can you confirm this is a direction you want to go? @fishbigger

**Comment by fishbigger** [comment]
Yes @kenhayward this is definitely the direction I want to add the p110 into the integration but I just don't have a plug to test it with or the time to do it. If you could add it and create a pull request I will merge it. Thanks.

**Comment by FluffyGhoster** [comment]
The library (https://pypi.org/project/PyP100/) already support P110, I believe it's just a matter of instantiating the object and expose the proprieties to HA, I'm however not familiar with HA
