### ISSUE TITLE
Error -1501 (invalid credentials) if pasword contain symbols

### ISSUE THREAD

**Issue by ghiki** [fishbigger/HomeAssistant-Tapo-P100-Control#42]
Error -1501 (invalid credentials) if pasword contain symbols
If you configure the addon and there are some symbols like "!" in the password fiel, the login doesn't work

**Comment by virgil9306** [comment]
did you try using `""` around the password and email

**Comment by fishbigger** [comment]
This is a known issue that I'm not sure how to fix it has been quite well documented [here](https://github.com/fishbigger/TapoP100/issues/4)
